version: '3.8'
services:
# Zookeeper service for Kafka cluster management
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
# Kafka service for message broker
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      # Kafka broker id: unique integer for each broker
      KAFKA_BROKER_ID: 1
      # Zookeeper connection string: it tells Kafka where to find Zookeeper
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Kafka listeners: it tells Kafka to listen on localhost:9092 with PLAINTEXT protocol
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # Kafka offsets topic replication factor: replication factor for the internal Kafka topic
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
